const WUXIA_NAMES = [
  'ShadowDragon',
  'JadeSword',
  'MoonPhoenix',
  'ThunderFist',
  'SilkViper',
  'CrimsonLotus',
  'IronMonk',
  'GoldenCrane',
  'FrostBlade',
  'WindWalker',
  'StormSage',
  'EmberTiger',
  'SilentArrow',
  'NightHawk',
  'StarForge',
  'DragonScale',
  'MistWarden',
  'BloodMoon',
  'PhoenixAsh',
  'VoidSeeker',
  'IceWolf',
  'FlameSpirit',
  'SteelPalm',
  'CloudRunner',
  'DarkOrchid',
  'LightBringer',
  'ThunderBolt',
  'SilverFox',
  'RedLotus',
  'IronWing',
  'ShadowFang',
  'JadeEmperor',
  'CelestialBlade',
  'SerpentKing',
  'AzurePhoenix',
  'GoldenDragon',
  'MysticSword',
  'FrostEmpress',
  'StormBreaker',
  'VenomClaw',
  'DivinePalm',
  'EternalFlame',
  'WhisperBlade',
  'BlackLotus',
  'TigerSoul',
  'MoonShadow',
  'SunWarden',
  'DeathBlossom',
  'SkyPiercer',
  'BoneForge',
];

export function generateGuestUsername(): string {
  const name = WUXIA_NAMES[Math.floor(Math.random() * WUXIA_NAMES.length)];
  const numbers = Math.floor(10000 + Math.random() * 90000);
  return `${name}${numbers}`;
}
