/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { DeleteKeywordsChaptersById200CreatedAt } from './deleteKeywordsChaptersById200CreatedAt';
import type { DeleteKeywordsChaptersById200UpdatedAt } from './deleteKeywordsChaptersById200UpdatedAt';

export type DeleteKeywordsChaptersById200 = {
  id: string;
  keywordId: string;
  chapterId: string;
  createdAt: DeleteKeywordsChaptersById200CreatedAt;
  updatedAt: DeleteKeywordsChaptersById200UpdatedAt;
};
