/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type DeleteReplacementsById200MatchingType = typeof DeleteReplacementsById200MatchingType[keyof typeof DeleteReplacementsById200MatchingType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteReplacementsById200MatchingType = {
  FULL: 'FULL',
  PARTIAL: 'PARTIAL',
} as const;
