/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { DeleteKeywordCategoriesById200CreatedAt } from './deleteKeywordCategoriesById200CreatedAt';
import type { DeleteKeywordCategoriesById200UpdatedAt } from './deleteKeywordCategoriesById200UpdatedAt';

export type DeleteKeywordCategoriesById200 = {
  id: string;
  name: string;
  color: string;
  createdAt: DeleteKeywordCategoriesById200CreatedAt;
  updatedAt: DeleteKeywordCategoriesById200UpdatedAt;
};
