/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { DeleteConfigsByKey200CreatedAt } from './deleteConfigsByKey200CreatedAt';
import type { DeleteConfigsByKey200UpdatedAt } from './deleteConfigsByKey200UpdatedAt';

export type DeleteConfigsByKey200 = {
  id: string;
  key: string;
  value: string;
  createdAt: DeleteConfigsByKey200CreatedAt;
  updatedAt: DeleteConfigsByKey200UpdatedAt;
};
