/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { DeleteChaptersById200Number } from './deleteChaptersById200Number';
import type { DeleteChaptersById200Description } from './deleteChaptersById200Description';
import type { DeleteChaptersById200CreatedAt } from './deleteChaptersById200CreatedAt';
import type { DeleteChaptersById200UpdatedAt } from './deleteChaptersById200UpdatedAt';

export type DeleteChaptersById200 = {
  id: string;
  name: string;
  number: DeleteChaptersById200Number;
  description: DeleteChaptersById200Description;
  novelId: string;
  createdAt: DeleteChaptersById200CreatedAt;
  updatedAt: DeleteChaptersById200UpdatedAt;
};
