/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetChaptersById200KeywordsChaptersItemKeywordCategoryCreatedAt } from './getChaptersById200KeywordsChaptersItemKeywordCategoryCreatedAt';
import type { GetChaptersById200KeywordsChaptersItemKeywordCategoryUpdatedAt } from './getChaptersById200KeywordsChaptersItemKeywordCategoryUpdatedAt';

export type GetChaptersById200KeywordsChaptersItemKeywordCategory = {
  id: string;
  name: string;
  color: string;
  createdAt: GetChaptersById200KeywordsChaptersItemKeywordCategoryCreatedAt;
  updatedAt: GetChaptersById200KeywordsChaptersItemKeywordCategoryUpdatedAt;
};
