/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetChaptersNovelByNovelId200DataItem } from './getChaptersNovelByNovelId200DataItem';

export type GetChaptersNovelByNovelId200 = {
  data: GetChaptersNovelByNovelId200DataItem[];
  total: number;
};
