/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetChaptersById200KeywordsChaptersItemKeywordImageAnyOf } from './getChaptersById200KeywordsChaptersItemKeywordImageAnyOf';

/**
 * @nullable
 */
export type GetChaptersById200KeywordsChaptersItemKeywordImage =
  GetChaptersById200KeywordsChaptersItemKeywordImageAnyOf | null | null;
