/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetChaptersById200KeywordsChaptersItemKeywordNatureCreatedAt } from './getChaptersById200KeywordsChaptersItemKeywordNatureCreatedAt';
import type { GetChaptersById200KeywordsChaptersItemKeywordNatureUpdatedAt } from './getChaptersById200KeywordsChaptersItemKeywordNatureUpdatedAt';

export type GetChaptersById200KeywordsChaptersItemKeywordNature = {
  id: string;
  name: string;
  color: string;
  createdAt: GetChaptersById200KeywordsChaptersItemKeywordNatureCreatedAt;
  updatedAt: GetChaptersById200KeywordsChaptersItemKeywordNatureUpdatedAt;
};
