/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetChaptersById200KeywordsChaptersItemCreatedAt } from './getChaptersById200KeywordsChaptersItemCreatedAt';
import type { GetChaptersById200KeywordsChaptersItemUpdatedAt } from './getChaptersById200KeywordsChaptersItemUpdatedAt';
import type { GetChaptersById200KeywordsChaptersItemKeyword } from './getChaptersById200KeywordsChaptersItemKeyword';

export type GetChaptersById200KeywordsChaptersItem = {
  id: string;
  keywordId: string;
  chapterId: string;
  createdAt: GetChaptersById200KeywordsChaptersItemCreatedAt;
  updatedAt: GetChaptersById200KeywordsChaptersItemUpdatedAt;
  keyword: GetChaptersById200KeywordsChaptersItemKeyword;
};
