/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetConfigsByKey200CreatedAt } from './getConfigsByKey200CreatedAt';
import type { GetConfigsByKey200UpdatedAt } from './getConfigsByKey200UpdatedAt';

export type GetConfigsByKey200 = {
  id: string;
  key: string;
  value: string;
  createdAt: GetConfigsByKey200CreatedAt;
  updatedAt: GetConfigsByKey200UpdatedAt;
};
