/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetConfigs200DataItem } from './getConfigs200DataItem';

export type GetConfigs200 = {
  data: GetConfigs200DataItem[];
};
