/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetChaptersNovelByNovelId200DataItemNumber } from './getChaptersNovelByNovelId200DataItemNumber';
import type { GetChaptersNovelByNovelId200DataItemDescription } from './getChaptersNovelByNovelId200DataItemDescription';
import type { GetChaptersNovelByNovelId200DataItemCreatedAt } from './getChaptersNovelByNovelId200DataItemCreatedAt';
import type { GetChaptersNovelByNovelId200DataItemUpdatedAt } from './getChaptersNovelByNovelId200DataItemUpdatedAt';

export type GetChaptersNovelByNovelId200DataItem = {
  id: string;
  name: string;
  number: GetChaptersNovelByNovelId200DataItemNumber;
  description: GetChaptersNovelByNovelId200DataItemDescription;
  novelId: string;
  createdAt: GetChaptersNovelByNovelId200DataItemCreatedAt;
  updatedAt: GetChaptersNovelByNovelId200DataItemUpdatedAt;
};
