/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type GetKeywordsById200ReplacementsItemMatchingType = typeof GetKeywordsById200ReplacementsItemMatchingType[keyof typeof GetKeywordsById200ReplacementsItemMatchingType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetKeywordsById200ReplacementsItemMatchingType = {
  FULL: 'FULL',
  PARTIAL: 'PARTIAL',
} as const;
