/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsChaptersById200ChapterNovelDescription } from './getKeywordsChaptersById200ChapterNovelDescription';
import type { GetKeywordsChaptersById200ChapterNovelImageId } from './getKeywordsChaptersById200ChapterNovelImageId';
import type { GetKeywordsChaptersById200ChapterNovelCreatedAt } from './getKeywordsChaptersById200ChapterNovelCreatedAt';
import type { GetKeywordsChaptersById200ChapterNovelUpdatedAt } from './getKeywordsChaptersById200ChapterNovelUpdatedAt';

export type GetKeywordsChaptersById200ChapterNovel = {
  id: string;
  name: string;
  description: GetKeywordsChaptersById200ChapterNovelDescription;
  slugs: string[];
  imageId: GetKeywordsChaptersById200ChapterNovelImageId;
  createdAt: GetKeywordsChaptersById200ChapterNovelCreatedAt;
  updatedAt: GetKeywordsChaptersById200ChapterNovelUpdatedAt;
};
