/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordCategories200DataItem } from './getKeywordCategories200DataItem';

export type GetKeywordCategories200 = {
  data: GetKeywordCategories200DataItem[];
  total: number;
};
