/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsChaptersById200KeywordNatureCreatedAt } from './getKeywordsChaptersById200KeywordNatureCreatedAt';
import type { GetKeywordsChaptersById200KeywordNatureUpdatedAt } from './getKeywordsChaptersById200KeywordNatureUpdatedAt';

export type GetKeywordsChaptersById200KeywordNature = {
  id: string;
  name: string;
  color: string;
  createdAt: GetKeywordsChaptersById200KeywordNatureCreatedAt;
  updatedAt: GetKeywordsChaptersById200KeywordNatureUpdatedAt;
};
