/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywords200DataItemParentAnyOfImageId } from './getKeywords200DataItemParentAnyOfImageId';
import type { GetKeywords200DataItemParentAnyOfParentId } from './getKeywords200DataItemParentAnyOfParentId';
import type { GetKeywords200DataItemParentAnyOfCreatedAt } from './getKeywords200DataItemParentAnyOfCreatedAt';
import type { GetKeywords200DataItemParentAnyOfUpdatedAt } from './getKeywords200DataItemParentAnyOfUpdatedAt';

export type GetKeywords200DataItemParentAnyOf = {
  id: string;
  name: string;
  description: string;
  categoryId: string;
  natureId: string;
  imageId: GetKeywords200DataItemParentAnyOfImageId;
  parentId: GetKeywords200DataItemParentAnyOfParentId;
  novelId: string;
  createdAt: GetKeywords200DataItemParentAnyOfCreatedAt;
  updatedAt: GetKeywords200DataItemParentAnyOfUpdatedAt;
};
