/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywords200DataItemParentAnyOf } from './getKeywords200DataItemParentAnyOf';

/**
 * @nullable
 */
export type GetKeywords200DataItemParent =
  GetKeywords200DataItemParentAnyOf | null | null;
