/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsById200ReplacementsItemMatchingType } from './getKeywordsById200ReplacementsItemMatchingType';
import type { GetKeywordsById200ReplacementsItemKeywordId } from './getKeywordsById200ReplacementsItemKeywordId';
import type { GetKeywordsById200ReplacementsItemCreatedById } from './getKeywordsById200ReplacementsItemCreatedById';
import type { GetKeywordsById200ReplacementsItemCreatedAt } from './getKeywordsById200ReplacementsItemCreatedAt';
import type { GetKeywordsById200ReplacementsItemUpdatedAt } from './getKeywordsById200ReplacementsItemUpdatedAt';

export type GetKeywordsById200ReplacementsItem = {
  id: string;
  from: string;
  to: string;
  matchingType: GetKeywordsById200ReplacementsItemMatchingType;
  novelId: string;
  keywordId: GetKeywordsById200ReplacementsItemKeywordId;
  createdById: GetKeywordsById200ReplacementsItemCreatedById;
  createdAt: GetKeywordsById200ReplacementsItemCreatedAt;
  updatedAt: GetKeywordsById200ReplacementsItemUpdatedAt;
};
