/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordNatures200DataItem } from './getKeywordNatures200DataItem';

export type GetKeywordNatures200 = {
  data: GetKeywordNatures200DataItem[];
  total: number;
};
