/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywords200DataItemImageAnyOf } from './getKeywords200DataItemImageAnyOf';

/**
 * @nullable
 */
export type GetKeywords200DataItemImage =
  GetKeywords200DataItemImageAnyOf | null | null;
