/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordNaturesById200KeywordsItemCategoryCreatedAt } from './getKeywordNaturesById200KeywordsItemCategoryCreatedAt';
import type { GetKeywordNaturesById200KeywordsItemCategoryUpdatedAt } from './getKeywordNaturesById200KeywordsItemCategoryUpdatedAt';

export type GetKeywordNaturesById200KeywordsItemCategory = {
  id: string;
  name: string;
  color: string;
  createdAt: GetKeywordNaturesById200KeywordsItemCategoryCreatedAt;
  updatedAt: GetKeywordNaturesById200KeywordsItemCategoryUpdatedAt;
};
