/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsChaptersById200KeywordImageId } from './getKeywordsChaptersById200KeywordImageId';
import type { GetKeywordsChaptersById200KeywordParentId } from './getKeywordsChaptersById200KeywordParentId';
import type { GetKeywordsChaptersById200KeywordCreatedAt } from './getKeywordsChaptersById200KeywordCreatedAt';
import type { GetKeywordsChaptersById200KeywordUpdatedAt } from './getKeywordsChaptersById200KeywordUpdatedAt';
import type { GetKeywordsChaptersById200KeywordCategory } from './getKeywordsChaptersById200KeywordCategory';
import type { GetKeywordsChaptersById200KeywordNature } from './getKeywordsChaptersById200KeywordNature';
import type { GetKeywordsChaptersById200KeywordImage } from './getKeywordsChaptersById200KeywordImage';

export type GetKeywordsChaptersById200Keyword = {
  id: string;
  name: string;
  description: string;
  categoryId: string;
  natureId: string;
  imageId: GetKeywordsChaptersById200KeywordImageId;
  parentId: GetKeywordsChaptersById200KeywordParentId;
  novelId: string;
  createdAt: GetKeywordsChaptersById200KeywordCreatedAt;
  updatedAt: GetKeywordsChaptersById200KeywordUpdatedAt;
  category: GetKeywordsChaptersById200KeywordCategory;
  nature: GetKeywordsChaptersById200KeywordNature;
  /** @nullable */
  image: GetKeywordsChaptersById200KeywordImage;
};
