/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsById200KeywordsChaptersItemChapterNumber } from './getKeywordsById200KeywordsChaptersItemChapterNumber';
import type { GetKeywordsById200KeywordsChaptersItemChapterDescription } from './getKeywordsById200KeywordsChaptersItemChapterDescription';
import type { GetKeywordsById200KeywordsChaptersItemChapterCreatedAt } from './getKeywordsById200KeywordsChaptersItemChapterCreatedAt';
import type { GetKeywordsById200KeywordsChaptersItemChapterUpdatedAt } from './getKeywordsById200KeywordsChaptersItemChapterUpdatedAt';

export type GetKeywordsById200KeywordsChaptersItemChapter = {
  id: string;
  name: string;
  number: GetKeywordsById200KeywordsChaptersItemChapterNumber;
  description: GetKeywordsById200KeywordsChaptersItemChapterDescription;
  novelId: string;
  createdAt: GetKeywordsById200KeywordsChaptersItemChapterCreatedAt;
  updatedAt: GetKeywordsById200KeywordsChaptersItemChapterUpdatedAt;
};
