/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsById200ParentAnyOfImageId } from './getKeywordsById200ParentAnyOfImageId';
import type { GetKeywordsById200ParentAnyOfParentId } from './getKeywordsById200ParentAnyOfParentId';
import type { GetKeywordsById200ParentAnyOfCreatedAt } from './getKeywordsById200ParentAnyOfCreatedAt';
import type { GetKeywordsById200ParentAnyOfUpdatedAt } from './getKeywordsById200ParentAnyOfUpdatedAt';

export type GetKeywordsById200ParentAnyOf = {
  id: string;
  name: string;
  description: string;
  categoryId: string;
  natureId: string;
  imageId: GetKeywordsById200ParentAnyOfImageId;
  parentId: GetKeywordsById200ParentAnyOfParentId;
  novelId: string;
  createdAt: GetKeywordsById200ParentAnyOfCreatedAt;
  updatedAt: GetKeywordsById200ParentAnyOfUpdatedAt;
};
