/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordNatures200DataItemCreatedAt } from './getKeywordNatures200DataItemCreatedAt';
import type { GetKeywordNatures200DataItemUpdatedAt } from './getKeywordNatures200DataItemUpdatedAt';

export type GetKeywordNatures200DataItem = {
  id: string;
  name: string;
  color: string;
  createdAt: GetKeywordNatures200DataItemCreatedAt;
  updatedAt: GetKeywordNatures200DataItemUpdatedAt;
};
