/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsById200CategoryCreatedAt } from './getKeywordsById200CategoryCreatedAt';
import type { GetKeywordsById200CategoryUpdatedAt } from './getKeywordsById200CategoryUpdatedAt';

export type GetKeywordsById200Category = {
  id: string;
  name: string;
  color: string;
  createdAt: GetKeywordsById200CategoryCreatedAt;
  updatedAt: GetKeywordsById200CategoryUpdatedAt;
};
