/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsChaptersById200KeywordImageAnyOf } from './getKeywordsChaptersById200KeywordImageAnyOf';

/**
 * @nullable
 */
export type GetKeywordsChaptersById200KeywordImage =
  GetKeywordsChaptersById200KeywordImageAnyOf | null | null;
