/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordCategories200DataItemCreatedAt } from './getKeywordCategories200DataItemCreatedAt';
import type { GetKeywordCategories200DataItemUpdatedAt } from './getKeywordCategories200DataItemUpdatedAt';

export type GetKeywordCategories200DataItem = {
  id: string;
  name: string;
  color: string;
  createdAt: GetKeywordCategories200DataItemCreatedAt;
  updatedAt: GetKeywordCategories200DataItemUpdatedAt;
};
