/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsChaptersById200KeywordImageAnyOfType } from './getKeywordsChaptersById200KeywordImageAnyOfType';
import type { GetKeywordsChaptersById200KeywordImageAnyOfUserId } from './getKeywordsChaptersById200KeywordImageAnyOfUserId';
import type { GetKeywordsChaptersById200KeywordImageAnyOfAdminId } from './getKeywordsChaptersById200KeywordImageAnyOfAdminId';
import type { GetKeywordsChaptersById200KeywordImageAnyOfCreatedAt } from './getKeywordsChaptersById200KeywordImageAnyOfCreatedAt';
import type { GetKeywordsChaptersById200KeywordImageAnyOfUpdatedAt } from './getKeywordsChaptersById200KeywordImageAnyOfUpdatedAt';

export type GetKeywordsChaptersById200KeywordImageAnyOf = {
  id: string;
  url: string;
  type: GetKeywordsChaptersById200KeywordImageAnyOfType;
  provider_image_id: string;
  delete_url: string;
  userId: GetKeywordsChaptersById200KeywordImageAnyOfUserId;
  adminId: GetKeywordsChaptersById200KeywordImageAnyOfAdminId;
  createdAt: GetKeywordsChaptersById200KeywordImageAnyOfCreatedAt;
  updatedAt: GetKeywordsChaptersById200KeywordImageAnyOfUpdatedAt;
};
