/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsChaptersById200CreatedAt } from './getKeywordsChaptersById200CreatedAt';
import type { GetKeywordsChaptersById200UpdatedAt } from './getKeywordsChaptersById200UpdatedAt';
import type { GetKeywordsChaptersById200Keyword } from './getKeywordsChaptersById200Keyword';
import type { GetKeywordsChaptersById200Chapter } from './getKeywordsChaptersById200Chapter';

export type GetKeywordsChaptersById200 = {
  id: string;
  keywordId: string;
  chapterId: string;
  createdAt: GetKeywordsChaptersById200CreatedAt;
  updatedAt: GetKeywordsChaptersById200UpdatedAt;
  keyword: GetKeywordsChaptersById200Keyword;
  chapter: GetKeywordsChaptersById200Chapter;
};
