/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsById200ChildrenItemCategoryCreatedAt } from './getKeywordsById200ChildrenItemCategoryCreatedAt';
import type { GetKeywordsById200ChildrenItemCategoryUpdatedAt } from './getKeywordsById200ChildrenItemCategoryUpdatedAt';

export type GetKeywordsById200ChildrenItemCategory = {
  id: string;
  name: string;
  color: string;
  createdAt: GetKeywordsById200ChildrenItemCategoryCreatedAt;
  updatedAt: GetKeywordsById200ChildrenItemCategoryUpdatedAt;
};
