/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsById200ImageAnyOfType } from './getKeywordsById200ImageAnyOfType';
import type { GetKeywordsById200ImageAnyOfUserId } from './getKeywordsById200ImageAnyOfUserId';
import type { GetKeywordsById200ImageAnyOfAdminId } from './getKeywordsById200ImageAnyOfAdminId';
import type { GetKeywordsById200ImageAnyOfCreatedAt } from './getKeywordsById200ImageAnyOfCreatedAt';
import type { GetKeywordsById200ImageAnyOfUpdatedAt } from './getKeywordsById200ImageAnyOfUpdatedAt';

export type GetKeywordsById200ImageAnyOf = {
  id: string;
  url: string;
  type: GetKeywordsById200ImageAnyOfType;
  provider_image_id: string;
  delete_url: string;
  userId: GetKeywordsById200ImageAnyOfUserId;
  adminId: GetKeywordsById200ImageAnyOfAdminId;
  createdAt: GetKeywordsById200ImageAnyOfCreatedAt;
  updatedAt: GetKeywordsById200ImageAnyOfUpdatedAt;
};
