/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordCategoriesSortingDirection } from './getKeywordCategoriesSortingDirection';

export type GetKeywordCategoriesParams = {
  pagination?: {
    page: number;
    pageSize: number;
  };
  sorting?: {
    column: string;
    direction?: GetKeywordCategoriesSortingDirection;
  };
};
