/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsById200ChildrenItemNatureCreatedAt } from './getKeywordsById200ChildrenItemNatureCreatedAt';
import type { GetKeywordsById200ChildrenItemNatureUpdatedAt } from './getKeywordsById200ChildrenItemNatureUpdatedAt';

export type GetKeywordsById200ChildrenItemNature = {
  id: string;
  name: string;
  color: string;
  createdAt: GetKeywordsById200ChildrenItemNatureCreatedAt;
  updatedAt: GetKeywordsById200ChildrenItemNatureUpdatedAt;
};
