/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsById200NovelAnyOf } from './getKeywordsById200NovelAnyOf';

/**
 * @nullable
 */
export type GetKeywordsById200Novel = GetKeywordsById200NovelAnyOf | null | null;
