/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsById200ChildrenItemImageId } from './getKeywordsById200ChildrenItemImageId';
import type { GetKeywordsById200ChildrenItemParentId } from './getKeywordsById200ChildrenItemParentId';
import type { GetKeywordsById200ChildrenItemCreatedAt } from './getKeywordsById200ChildrenItemCreatedAt';
import type { GetKeywordsById200ChildrenItemUpdatedAt } from './getKeywordsById200ChildrenItemUpdatedAt';
import type { GetKeywordsById200ChildrenItemCategory } from './getKeywordsById200ChildrenItemCategory';
import type { GetKeywordsById200ChildrenItemNature } from './getKeywordsById200ChildrenItemNature';

export type GetKeywordsById200ChildrenItem = {
  id: string;
  name: string;
  description: string;
  categoryId: string;
  natureId: string;
  imageId: GetKeywordsById200ChildrenItemImageId;
  parentId: GetKeywordsById200ChildrenItemParentId;
  novelId: string;
  createdAt: GetKeywordsById200ChildrenItemCreatedAt;
  updatedAt: GetKeywordsById200ChildrenItemUpdatedAt;
  category: GetKeywordsById200ChildrenItemCategory;
  nature: GetKeywordsById200ChildrenItemNature;
};
