/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsById200NatureCreatedAt } from './getKeywordsById200NatureCreatedAt';
import type { GetKeywordsById200NatureUpdatedAt } from './getKeywordsById200NatureUpdatedAt';

export type GetKeywordsById200Nature = {
  id: string;
  name: string;
  color: string;
  createdAt: GetKeywordsById200NatureCreatedAt;
  updatedAt: GetKeywordsById200NatureUpdatedAt;
};
