/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsSortingDirection } from './getKeywordsSortingDirection';

export type GetKeywordsParams = {
  pagination?: {
    page: number;
    pageSize: number;
  };
  sorting?: {
    column: string;
    direction?: GetKeywordsSortingDirection;
  };
  query?: {
    search?: string;
    categoryId?: string;
    natureId?: string;
    novelId?: string;
  };
};
