/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsById200ImageAnyOf } from './getKeywordsById200ImageAnyOf';

/**
 * @nullable
 */
export type GetKeywordsById200Image = GetKeywordsById200ImageAnyOf | null | null;
