/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsChaptersById200ChapterNumber } from './getKeywordsChaptersById200ChapterNumber';
import type { GetKeywordsChaptersById200ChapterDescription } from './getKeywordsChaptersById200ChapterDescription';
import type { GetKeywordsChaptersById200ChapterCreatedAt } from './getKeywordsChaptersById200ChapterCreatedAt';
import type { GetKeywordsChaptersById200ChapterUpdatedAt } from './getKeywordsChaptersById200ChapterUpdatedAt';
import type { GetKeywordsChaptersById200ChapterNovel } from './getKeywordsChaptersById200ChapterNovel';

export type GetKeywordsChaptersById200Chapter = {
  id: string;
  name: string;
  number: GetKeywordsChaptersById200ChapterNumber;
  description: GetKeywordsChaptersById200ChapterDescription;
  novelId: string;
  createdAt: GetKeywordsChaptersById200ChapterCreatedAt;
  updatedAt: GetKeywordsChaptersById200ChapterUpdatedAt;
  novel: GetKeywordsChaptersById200ChapterNovel;
};
