/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywords200DataItemNatureCreatedAt } from './getKeywords200DataItemNatureCreatedAt';
import type { GetKeywords200DataItemNatureUpdatedAt } from './getKeywords200DataItemNatureUpdatedAt';

export type GetKeywords200DataItemNature = {
  id: string;
  name: string;
  color: string;
  createdAt: GetKeywords200DataItemNatureCreatedAt;
  updatedAt: GetKeywords200DataItemNatureUpdatedAt;
};
