/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordCategoriesById200KeywordsItemMatchingType } from './getKeywordCategoriesById200KeywordsItemMatchingType';
import type { GetKeywordCategoriesById200KeywordsItemImageId } from './getKeywordCategoriesById200KeywordsItemImageId';
import type { GetKeywordCategoriesById200KeywordsItemParentId } from './getKeywordCategoriesById200KeywordsItemParentId';
import type { GetKeywordCategoriesById200KeywordsItemCreatedById } from './getKeywordCategoriesById200KeywordsItemCreatedById';
import type { GetKeywordCategoriesById200KeywordsItemCreatedAt } from './getKeywordCategoriesById200KeywordsItemCreatedAt';
import type { GetKeywordCategoriesById200KeywordsItemUpdatedAt } from './getKeywordCategoriesById200KeywordsItemUpdatedAt';
import type { GetKeywordCategoriesById200KeywordsItemNature } from './getKeywordCategoriesById200KeywordsItemNature';

export type GetKeywordCategoriesById200KeywordsItem = {
  id: string;
  name: string;
  description: string;
  matchingType: GetKeywordCategoriesById200KeywordsItemMatchingType;
  categoryId: string;
  natureId: string;
  imageId: GetKeywordCategoriesById200KeywordsItemImageId;
  parentId: GetKeywordCategoriesById200KeywordsItemParentId;
  novelId: string;
  createdById: GetKeywordCategoriesById200KeywordsItemCreatedById;
  createdAt: GetKeywordCategoriesById200KeywordsItemCreatedAt;
  updatedAt: GetKeywordCategoriesById200KeywordsItemUpdatedAt;
  nature: GetKeywordCategoriesById200KeywordsItemNature;
};
