/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

import type { _GetKeywordNaturesById200Count } from "./_getKeywordNaturesById200Count";
import type { GetKeywordNaturesById200CreatedAt } from "./getKeywordNaturesById200CreatedAt";
import type { GetKeywordNaturesById200KeywordsItem } from "./getKeywordNaturesById200KeywordsItem";
import type { GetKeywordNaturesById200UpdatedAt } from "./getKeywordNaturesById200UpdatedAt";

export type GetKeywordNaturesById200 = {
	id: string;
	name: string;
	color: string;
	createdAt: GetKeywordNaturesById200CreatedAt;
	updatedAt: GetKeywordNaturesById200UpdatedAt;
	keywords: GetKeywordNaturesById200KeywordsItem[];
	_count: _GetKeywordNaturesById200Count;
};
