/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsById200ImageId } from './getKeywordsById200ImageId';
import type { GetKeywordsById200ParentId } from './getKeywordsById200ParentId';
import type { GetKeywordsById200CreatedAt } from './getKeywordsById200CreatedAt';
import type { GetKeywordsById200UpdatedAt } from './getKeywordsById200UpdatedAt';
import type { GetKeywordsById200Category } from './getKeywordsById200Category';
import type { GetKeywordsById200Nature } from './getKeywordsById200Nature';
import type { GetKeywordsById200Image } from './getKeywordsById200Image';
import type { GetKeywordsById200Parent } from './getKeywordsById200Parent';
import type { GetKeywordsById200ChildrenItem } from './getKeywordsById200ChildrenItem';
import type { GetKeywordsById200Novel } from './getKeywordsById200Novel';
import type { GetKeywordsById200KeywordsChaptersItem } from './getKeywordsById200KeywordsChaptersItem';
import type { GetKeywordsById200ReplacementsItem } from './getKeywordsById200ReplacementsItem';

export type GetKeywordsById200 = {
  id: string;
  name: string;
  description: string;
  categoryId: string;
  natureId: string;
  imageId: GetKeywordsById200ImageId;
  parentId: GetKeywordsById200ParentId;
  novelId: string;
  createdAt: GetKeywordsById200CreatedAt;
  updatedAt: GetKeywordsById200UpdatedAt;
  category: GetKeywordsById200Category;
  nature: GetKeywordsById200Nature;
  /** @nullable */
  image: GetKeywordsById200Image;
  /** @nullable */
  parent: GetKeywordsById200Parent;
  children: GetKeywordsById200ChildrenItem[];
  /** @nullable */
  novel: GetKeywordsById200Novel;
  KeywordsChapters: GetKeywordsById200KeywordsChaptersItem[];
  replacements: GetKeywordsById200ReplacementsItem[];
};
