/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsChaptersKeywordByKeywordId200DataItem } from './getKeywordsChaptersKeywordByKeywordId200DataItem';

export type GetKeywordsChaptersKeywordByKeywordId200 = {
  data: GetKeywordsChaptersKeywordByKeywordId200DataItem[];
  total: number;
};
