/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsById200ParentAnyOf } from './getKeywordsById200ParentAnyOf';

/**
 * @nullable
 */
export type GetKeywordsById200Parent = GetKeywordsById200ParentAnyOf | null | null;
