/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywords200DataItemImageAnyOfType } from './getKeywords200DataItemImageAnyOfType';
import type { GetKeywords200DataItemImageAnyOfUserId } from './getKeywords200DataItemImageAnyOfUserId';
import type { GetKeywords200DataItemImageAnyOfAdminId } from './getKeywords200DataItemImageAnyOfAdminId';
import type { GetKeywords200DataItemImageAnyOfCreatedAt } from './getKeywords200DataItemImageAnyOfCreatedAt';
import type { GetKeywords200DataItemImageAnyOfUpdatedAt } from './getKeywords200DataItemImageAnyOfUpdatedAt';

export type GetKeywords200DataItemImageAnyOf = {
  id: string;
  url: string;
  type: GetKeywords200DataItemImageAnyOfType;
  provider_image_id: string;
  delete_url: string;
  userId: GetKeywords200DataItemImageAnyOfUserId;
  adminId: GetKeywords200DataItemImageAnyOfAdminId;
  createdAt: GetKeywords200DataItemImageAnyOfCreatedAt;
  updatedAt: GetKeywords200DataItemImageAnyOfUpdatedAt;
};
