/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywords200DataItem } from './getKeywords200DataItem';

export type GetKeywords200 = {
  data: GetKeywords200DataItem[];
  total: number;
};
