/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywords200DataItemCategoryCreatedAt } from './getKeywords200DataItemCategoryCreatedAt';
import type { GetKeywords200DataItemCategoryUpdatedAt } from './getKeywords200DataItemCategoryUpdatedAt';

export type GetKeywords200DataItemCategory = {
  id: string;
  name: string;
  color: string;
  createdAt: GetKeywords200DataItemCategoryCreatedAt;
  updatedAt: GetKeywords200DataItemCategoryUpdatedAt;
};
