/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetKeywordsChaptersChapterByChapterId200DataItem } from './getKeywordsChaptersChapterByChapterId200DataItem';

export type GetKeywordsChaptersChapterByChapterId200 = {
  data: GetKeywordsChaptersChapterByChapterId200DataItem[];
  total: number;
};
