/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetNovelsById200ImageAnyOf } from './getNovelsById200ImageAnyOf';

/**
 * @nullable
 */
export type GetNovelsById200Image = GetNovelsById200ImageAnyOf | null | null;
