/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetNovelsSortingDirection } from './getNovelsSortingDirection';

export type GetNovelsParams = {
  pagination?: {
    page: number;
    pageSize: number;
  };
  sorting?: {
    column: string;
    direction?: GetNovelsSortingDirection;
  };
  query?: {
    search?: string;
  };
};
