/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetNovels200DataItem } from './getNovels200DataItem';

export type GetNovels200 = {
  data: GetNovels200DataItem[];
  total: number;
};
