/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetNovelsById200ChaptersItemNumber } from './getNovelsById200ChaptersItemNumber';
import type { GetNovelsById200ChaptersItemDescription } from './getNovelsById200ChaptersItemDescription';
import type { GetNovelsById200ChaptersItemCreatedAt } from './getNovelsById200ChaptersItemCreatedAt';
import type { GetNovelsById200ChaptersItemUpdatedAt } from './getNovelsById200ChaptersItemUpdatedAt';

export type GetNovelsById200ChaptersItem = {
  id: string;
  name: string;
  number: GetNovelsById200ChaptersItemNumber;
  description: GetNovelsById200ChaptersItemDescription;
  novelId: string;
  createdAt: GetNovelsById200ChaptersItemCreatedAt;
  updatedAt: GetNovelsById200ChaptersItemUpdatedAt;
};
