/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

import type { GetNovelsById200ChaptersItem } from "./getNovelsById200ChaptersItem";
import type { GetNovelsById200CreatedAt } from "./getNovelsById200CreatedAt";
import type { GetNovelsById200Description } from "./getNovelsById200Description";
import type { GetNovelsById200Image } from "./getNovelsById200Image";
import type { GetNovelsById200ImageId } from "./getNovelsById200ImageId";
import type { GetNovelsById200UpdatedAt } from "./getNovelsById200UpdatedAt";

export type GetNovelsById200 = {
	id: string;
	name: string;
	description: GetNovelsById200Description;
	slugs: string[];
	imageId: GetNovelsById200ImageId;
	createdAt: GetNovelsById200CreatedAt;
	updatedAt: GetNovelsById200UpdatedAt;
	/** @nullable */
	image: GetNovelsById200Image;
	chapters: GetNovelsById200ChaptersItem[];
};
