/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetReplacementsById200KeywordAnyOfCategoryCreatedAt } from './getReplacementsById200KeywordAnyOfCategoryCreatedAt';
import type { GetReplacementsById200KeywordAnyOfCategoryUpdatedAt } from './getReplacementsById200KeywordAnyOfCategoryUpdatedAt';

export type GetReplacementsById200KeywordAnyOfCategory = {
  id: string;
  name: string;
  color: string;
  createdAt: GetReplacementsById200KeywordAnyOfCategoryCreatedAt;
  updatedAt: GetReplacementsById200KeywordAnyOfCategoryUpdatedAt;
};
