/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetReplacementsById200KeywordAnyOf } from './getReplacementsById200KeywordAnyOf';

/**
 * @nullable
 */
export type GetReplacementsById200Keyword =
  GetReplacementsById200KeywordAnyOf | null | null;
