/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetReplacements200DataItem } from './getReplacements200DataItem';

export type GetReplacements200 = {
  data: GetReplacements200DataItem[];
  total: number;
};
