/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type GetReplacementsSortingDirection = typeof GetReplacementsSortingDirection[keyof typeof GetReplacementsSortingDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetReplacementsSortingDirection = {
  asc: 'asc',
  desc: 'desc',
} as const;
