/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetReplacements200DataItemKeywordAnyOf } from './getReplacements200DataItemKeywordAnyOf';

/**
 * @nullable
 */
export type GetReplacements200DataItemKeyword =
  GetReplacements200DataItemKeywordAnyOf | null | null;
