/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetReplacements200DataItemKeywordAnyOfImageId } from './getReplacements200DataItemKeywordAnyOfImageId';
import type { GetReplacements200DataItemKeywordAnyOfParentId } from './getReplacements200DataItemKeywordAnyOfParentId';
import type { GetReplacements200DataItemKeywordAnyOfCreatedAt } from './getReplacements200DataItemKeywordAnyOfCreatedAt';
import type { GetReplacements200DataItemKeywordAnyOfUpdatedAt } from './getReplacements200DataItemKeywordAnyOfUpdatedAt';

export type GetReplacements200DataItemKeywordAnyOf = {
  id: string;
  name: string;
  description: string;
  categoryId: string;
  natureId: string;
  imageId: GetReplacements200DataItemKeywordAnyOfImageId;
  parentId: GetReplacements200DataItemKeywordAnyOfParentId;
  novelId: string;
  createdAt: GetReplacements200DataItemKeywordAnyOfCreatedAt;
  updatedAt: GetReplacements200DataItemKeywordAnyOfUpdatedAt;
};
