/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetReplacements200DataItemKeywordId } from './getReplacements200DataItemKeywordId';
import type { GetReplacements200DataItemCreatedAt } from './getReplacements200DataItemCreatedAt';
import type { GetReplacements200DataItemUpdatedAt } from './getReplacements200DataItemUpdatedAt';
import type { GetReplacements200DataItemKeyword } from './getReplacements200DataItemKeyword';

export type GetReplacements200DataItem = {
  id: string;
  from: string;
  to: string;
  novelId: string;
  keywordId: GetReplacements200DataItemKeywordId;
  createdAt: GetReplacements200DataItemCreatedAt;
  updatedAt: GetReplacements200DataItemUpdatedAt;
  /** @nullable */
  keyword: GetReplacements200DataItemKeyword;
};
