/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetReplacementsKeywordByKeywordId200DataItemKeywordId } from './getReplacementsKeywordByKeywordId200DataItemKeywordId';
import type { GetReplacementsKeywordByKeywordId200DataItemCreatedAt } from './getReplacementsKeywordByKeywordId200DataItemCreatedAt';
import type { GetReplacementsKeywordByKeywordId200DataItemUpdatedAt } from './getReplacementsKeywordByKeywordId200DataItemUpdatedAt';

export type GetReplacementsKeywordByKeywordId200DataItem = {
  id: string;
  replacement: string;
  novelId: string;
  keywordId: GetReplacementsKeywordByKeywordId200DataItemKeywordId;
  createdAt: GetReplacementsKeywordByKeywordId200DataItemCreatedAt;
  updatedAt: GetReplacementsKeywordByKeywordId200DataItemUpdatedAt;
};
