/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetReplacementsKeywordByKeywordId200DataItem } from './getReplacementsKeywordByKeywordId200DataItem';

export type GetReplacementsKeywordByKeywordId200 = {
  data: GetReplacementsKeywordByKeywordId200DataItem[];
  total: number;
};
