/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetReplacementsSortingDirection } from './getReplacementsSortingDirection';

export type GetReplacementsParams = {
  pagination?: {
    page: number;
    pageSize: number;
  };
  sorting?: {
    column: string;
    direction?: GetReplacementsSortingDirection;
  };
  query?: {
    search?: string;
    from?: string;
    to?: string;
    novelId?: string;
    keywordId?: string;
  };
};
