/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type GetReplacements200DataItemKeywordAnyOfCreatedAt =
  | unknown
  | string
  | string
  | number;
