/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type PostReplacements200MatchingType = typeof PostReplacements200MatchingType[keyof typeof PostReplacements200MatchingType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostReplacements200MatchingType = {
  FULL: 'FULL',
  PARTIAL: 'PARTIAL',
} as const;
