/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostReplacements200KeywordAnyOf } from './postReplacements200KeywordAnyOf';

/**
 * @nullable
 */
export type PostReplacements200Keyword =
  PostReplacements200KeywordAnyOf | null | null;
