/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostNovels200ImageAnyOf } from './postNovels200ImageAnyOf';

/**
 * @nullable
 */
export type PostNovels200Image = PostNovels200ImageAnyOf | null | null;
