/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostAiChapterSelectors200ResultSelectorsNovelXpathAnyOf } from './postAiChapterSelectors200ResultSelectorsNovelXpathAnyOf';

/**
 * @nullable
 */
export type PostAiChapterSelectors200ResultSelectorsNovelXpath = PostAiChapterSelectors200ResultSelectorsNovelXpathAnyOf | null | null;
