/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostFilesUploadBodyOneType } from './postFilesUploadBodyOneType';

export type PostFilesUploadBodyOne = {
  file: Blob;
  type: PostFilesUploadBodyOneType;
};
