/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostKeywords200CategoryCreatedAt } from './postKeywords200CategoryCreatedAt';
import type { PostKeywords200CategoryUpdatedAt } from './postKeywords200CategoryUpdatedAt';

export type PostKeywords200Category = {
  id: string;
  name: string;
  color: string;
  createdAt: PostKeywords200CategoryCreatedAt;
  updatedAt: PostKeywords200CategoryUpdatedAt;
};
