/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostKeywords200ParentAnyOf } from './postKeywords200ParentAnyOf';

/**
 * @nullable
 */
export type PostKeywords200Parent = PostKeywords200ParentAnyOf | null | null;
