/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostReplacementsBodyOneMatchingType } from './postReplacementsBodyOneMatchingType';

export type PostReplacementsBodyOne = {
  novelId: string;
  /** @minLength 1 */
  from: string;
  /** @minLength 1 */
  to: string;
  matchingType?: PostReplacementsBodyOneMatchingType;
};
