/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostFilesUploadBodyTwoType } from './postFilesUploadBodyTwoType';

export type PostFilesUploadBodyTwo = {
  file: Blob;
  type: PostFilesUploadBodyTwoType;
};
