/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type PostKeywords200MatchingType = typeof PostKeywords200MatchingType[keyof typeof PostKeywords200MatchingType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostKeywords200MatchingType = {
  FULL: 'FULL',
  PARTIAL: 'PARTIAL',
} as const;
