/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type PostKeywordsChapters200KeywordMatchingType = typeof PostKeywordsChapters200KeywordMatchingType[keyof typeof PostKeywordsChapters200KeywordMatchingType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostKeywordsChapters200KeywordMatchingType = {
  FULL: 'FULL',
  PARTIAL: 'PARTIAL',
} as const;
