/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostKeywords200ParentAnyOfImageId } from './postKeywords200ParentAnyOfImageId';
import type { PostKeywords200ParentAnyOfParentId } from './postKeywords200ParentAnyOfParentId';
import type { PostKeywords200ParentAnyOfCreatedAt } from './postKeywords200ParentAnyOfCreatedAt';
import type { PostKeywords200ParentAnyOfUpdatedAt } from './postKeywords200ParentAnyOfUpdatedAt';

export type PostKeywords200ParentAnyOf = {
  id: string;
  name: string;
  description: string;
  categoryId: string;
  natureId: string;
  imageId: PostKeywords200ParentAnyOfImageId;
  parentId: PostKeywords200ParentAnyOfParentId;
  novelId: string;
  createdAt: PostKeywords200ParentAnyOfCreatedAt;
  updatedAt: PostKeywords200ParentAnyOfUpdatedAt;
};
