/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostChapters200Number } from './postChapters200Number';
import type { PostChapters200Description } from './postChapters200Description';
import type { PostChapters200CreatedAt } from './postChapters200CreatedAt';
import type { PostChapters200UpdatedAt } from './postChapters200UpdatedAt';

export type PostChapters200 = {
  id: string;
  name: string;
  number: PostChapters200Number;
  description: PostChapters200Description;
  novelId: string;
  createdAt: PostChapters200CreatedAt;
  updatedAt: PostChapters200UpdatedAt;
};
