/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostFilesUpload200Type } from './postFilesUpload200Type';
import type { PostFilesUpload200UserId } from './postFilesUpload200UserId';
import type { PostFilesUpload200AdminId } from './postFilesUpload200AdminId';
import type { PostFilesUpload200CreatedAt } from './postFilesUpload200CreatedAt';
import type { PostFilesUpload200UpdatedAt } from './postFilesUpload200UpdatedAt';

export type PostFilesUpload200 = {
  id: string;
  url: string;
  type: PostFilesUpload200Type;
  provider_image_id: string;
  delete_url: string;
  userId: PostFilesUpload200UserId;
  adminId: PostFilesUpload200AdminId;
  createdAt: PostFilesUpload200CreatedAt;
  updatedAt: PostFilesUpload200UpdatedAt;
};
