/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostAiChapterSelectors200ResultSelectorsNovel } from './postAiChapterSelectors200ResultSelectorsNovel';
import type { PostAiChapterSelectors200ResultSelectorsChapter } from './postAiChapterSelectors200ResultSelectorsChapter';

export type PostAiChapterSelectors200ResultSelectors = {
  website: string;
  novel: PostAiChapterSelectors200ResultSelectorsNovel;
  chapter: PostAiChapterSelectors200ResultSelectorsChapter;
};
