/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostKeywords200ImageAnyOfType } from './postKeywords200ImageAnyOfType';
import type { PostKeywords200ImageAnyOfUserId } from './postKeywords200ImageAnyOfUserId';
import type { PostKeywords200ImageAnyOfAdminId } from './postKeywords200ImageAnyOfAdminId';
import type { PostKeywords200ImageAnyOfCreatedAt } from './postKeywords200ImageAnyOfCreatedAt';
import type { PostKeywords200ImageAnyOfUpdatedAt } from './postKeywords200ImageAnyOfUpdatedAt';

export type PostKeywords200ImageAnyOf = {
  id: string;
  url: string;
  type: PostKeywords200ImageAnyOfType;
  provider_image_id: string;
  delete_url: string;
  userId: PostKeywords200ImageAnyOfUserId;
  adminId: PostKeywords200ImageAnyOfAdminId;
  createdAt: PostKeywords200ImageAnyOfCreatedAt;
  updatedAt: PostKeywords200ImageAnyOfUpdatedAt;
};
