/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostAiChapterSelectors200ResultSelectors } from './postAiChapterSelectors200ResultSelectors';
import type { PostAiChapterSelectors200ResultNovelForm } from './postAiChapterSelectors200ResultNovelForm';
import type { PostAiChapterSelectors200ResultConfidence } from './postAiChapterSelectors200ResultConfidence';

export type PostAiChapterSelectors200Result = {
  website: string;
  selectors: PostAiChapterSelectors200ResultSelectors;
  novelForm: PostAiChapterSelectors200ResultNovelForm;
  confidence: PostAiChapterSelectors200ResultConfidence;
  notes?: string;
};
