/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type PostReplacementsBodyOne = {
  novelId: string;
  /** @minLength 1 */
  from: string;
  /** @minLength 1 */
  to: string;
};
