/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostKeywords200ImageAnyOf } from './postKeywords200ImageAnyOf';

/**
 * @nullable
 */
export type PostKeywords200Image = PostKeywords200ImageAnyOf | null | null;
