/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type PostReplacementsBodyTwoMatchingType = typeof PostReplacementsBodyTwoMatchingType[keyof typeof PostReplacementsBodyTwoMatchingType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostReplacementsBodyTwoMatchingType = {
  FULL: 'FULL',
  PARTIAL: 'PARTIAL',
} as const;
