/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostKeywords200NatureCreatedAt } from './postKeywords200NatureCreatedAt';
import type { PostKeywords200NatureUpdatedAt } from './postKeywords200NatureUpdatedAt';

export type PostKeywords200Nature = {
  id: string;
  name: string;
  color: string;
  createdAt: PostKeywords200NatureCreatedAt;
  updatedAt: PostKeywords200NatureUpdatedAt;
};
