/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostKeywordsChapters200KeywordImageId } from './postKeywordsChapters200KeywordImageId';
import type { PostKeywordsChapters200KeywordParentId } from './postKeywordsChapters200KeywordParentId';
import type { PostKeywordsChapters200KeywordCreatedAt } from './postKeywordsChapters200KeywordCreatedAt';
import type { PostKeywordsChapters200KeywordUpdatedAt } from './postKeywordsChapters200KeywordUpdatedAt';

export type PostKeywordsChapters200Keyword = {
  id: string;
  name: string;
  description: string;
  categoryId: string;
  natureId: string;
  imageId: PostKeywordsChapters200KeywordImageId;
  parentId: PostKeywordsChapters200KeywordParentId;
  novelId: string;
  createdAt: PostKeywordsChapters200KeywordCreatedAt;
  updatedAt: PostKeywordsChapters200KeywordUpdatedAt;
};
