/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PutChaptersById200Number } from './putChaptersById200Number';
import type { PutChaptersById200Description } from './putChaptersById200Description';
import type { PutChaptersById200CreatedAt } from './putChaptersById200CreatedAt';
import type { PutChaptersById200UpdatedAt } from './putChaptersById200UpdatedAt';

export type PutChaptersById200 = {
  id: string;
  name: string;
  number: PutChaptersById200Number;
  description: PutChaptersById200Description;
  novelId: string;
  createdAt: PutChaptersById200CreatedAt;
  updatedAt: PutChaptersById200UpdatedAt;
};
