/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type PutChaptersByIdBodyOne = {
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  number: number;
  description?: string;
};
