/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type PutKeywordsByIdBodyOne = {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  categoryId: string;
  natureId: string;
  imageId?: string;
  parentId?: string;
};
