/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PutKeywordsById200ParentAnyOfImageId } from './putKeywordsById200ParentAnyOfImageId';
import type { PutKeywordsById200ParentAnyOfParentId } from './putKeywordsById200ParentAnyOfParentId';
import type { PutKeywordsById200ParentAnyOfCreatedAt } from './putKeywordsById200ParentAnyOfCreatedAt';
import type { PutKeywordsById200ParentAnyOfUpdatedAt } from './putKeywordsById200ParentAnyOfUpdatedAt';

export type PutKeywordsById200ParentAnyOf = {
  id: string;
  name: string;
  description: string;
  categoryId: string;
  natureId: string;
  imageId: PutKeywordsById200ParentAnyOfImageId;
  parentId: PutKeywordsById200ParentAnyOfParentId;
  novelId: string;
  createdAt: PutKeywordsById200ParentAnyOfCreatedAt;
  updatedAt: PutKeywordsById200ParentAnyOfUpdatedAt;
};
