/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PutKeywordsById200NatureCreatedAt } from './putKeywordsById200NatureCreatedAt';
import type { PutKeywordsById200NatureUpdatedAt } from './putKeywordsById200NatureUpdatedAt';

export type PutKeywordsById200Nature = {
  id: string;
  name: string;
  color: string;
  createdAt: PutKeywordsById200NatureCreatedAt;
  updatedAt: PutKeywordsById200NatureUpdatedAt;
};
