/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PutKeywordsById200ParentAnyOf } from './putKeywordsById200ParentAnyOf';

/**
 * @nullable
 */
export type PutKeywordsById200Parent = PutKeywordsById200ParentAnyOf | null | null;
