/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type PutKeywordCategoriesByIdBodyThree = {
  /** @minLength 1 */
  name: string;
  /** @pattern ^#[0-9A-Fa-f]{6}$ */
  color: string;
};
