/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PutKeywordsById200ImageAnyOf } from './putKeywordsById200ImageAnyOf';

/**
 * @nullable
 */
export type PutKeywordsById200Image = PutKeywordsById200ImageAnyOf | null | null;
