/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PutKeywordsById200ImageId } from './putKeywordsById200ImageId';
import type { PutKeywordsById200ParentId } from './putKeywordsById200ParentId';
import type { PutKeywordsById200CreatedAt } from './putKeywordsById200CreatedAt';
import type { PutKeywordsById200UpdatedAt } from './putKeywordsById200UpdatedAt';
import type { PutKeywordsById200Category } from './putKeywordsById200Category';
import type { PutKeywordsById200Nature } from './putKeywordsById200Nature';
import type { PutKeywordsById200Image } from './putKeywordsById200Image';
import type { PutKeywordsById200Parent } from './putKeywordsById200Parent';

export type PutKeywordsById200 = {
  id: string;
  name: string;
  description: string;
  categoryId: string;
  natureId: string;
  imageId: PutKeywordsById200ImageId;
  parentId: PutKeywordsById200ParentId;
  novelId: string;
  createdAt: PutKeywordsById200CreatedAt;
  updatedAt: PutKeywordsById200UpdatedAt;
  category: PutKeywordsById200Category;
  nature: PutKeywordsById200Nature;
  /** @nullable */
  image: PutKeywordsById200Image;
  /** @nullable */
  parent: PutKeywordsById200Parent;
};
