/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PutNovelsById200ImageAnyOf } from './putNovelsById200ImageAnyOf';

/**
 * @nullable
 */
export type PutNovelsById200Image = PutNovelsById200ImageAnyOf | null | null;
