/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PutNovelsById200ImageAnyOfType } from './putNovelsById200ImageAnyOfType';
import type { PutNovelsById200ImageAnyOfUserId } from './putNovelsById200ImageAnyOfUserId';
import type { PutNovelsById200ImageAnyOfAdminId } from './putNovelsById200ImageAnyOfAdminId';
import type { PutNovelsById200ImageAnyOfCreatedAt } from './putNovelsById200ImageAnyOfCreatedAt';
import type { PutNovelsById200ImageAnyOfUpdatedAt } from './putNovelsById200ImageAnyOfUpdatedAt';

export type PutNovelsById200ImageAnyOf = {
  id: string;
  url: string;
  type: PutNovelsById200ImageAnyOfType;
  provider_image_id: string;
  delete_url: string;
  userId: PutNovelsById200ImageAnyOfUserId;
  adminId: PutNovelsById200ImageAnyOfAdminId;
  createdAt: PutNovelsById200ImageAnyOfCreatedAt;
  updatedAt: PutNovelsById200ImageAnyOfUpdatedAt;
};
