/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PutReplacementsById200KeywordAnyOf } from './putReplacementsById200KeywordAnyOf';

/**
 * @nullable
 */
export type PutReplacementsById200Keyword = PutReplacementsById200KeywordAnyOf | null | null;
