/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PutReplacementsById200KeywordId } from './putReplacementsById200KeywordId';
import type { PutReplacementsById200CreatedAt } from './putReplacementsById200CreatedAt';
import type { PutReplacementsById200UpdatedAt } from './putReplacementsById200UpdatedAt';
import type { PutReplacementsById200Keyword } from './putReplacementsById200Keyword';

export type PutReplacementsById200 = {
  id: string;
  from: string;
  to: string;
  novelId: string;
  keywordId: PutReplacementsById200KeywordId;
  createdAt: PutReplacementsById200CreatedAt;
  updatedAt: PutReplacementsById200UpdatedAt;
  /** @nullable */
  keyword: PutReplacementsById200Keyword;
};
