/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PutReplacementsById200KeywordAnyOfMatchingType } from './putReplacementsById200KeywordAnyOfMatchingType';
import type { PutReplacementsById200KeywordAnyOfImageId } from './putReplacementsById200KeywordAnyOfImageId';
import type { PutReplacementsById200KeywordAnyOfParentId } from './putReplacementsById200KeywordAnyOfParentId';
import type { PutReplacementsById200KeywordAnyOfCreatedById } from './putReplacementsById200KeywordAnyOfCreatedById';
import type { PutReplacementsById200KeywordAnyOfCreatedAt } from './putReplacementsById200KeywordAnyOfCreatedAt';
import type { PutReplacementsById200KeywordAnyOfUpdatedAt } from './putReplacementsById200KeywordAnyOfUpdatedAt';

export type PutReplacementsById200KeywordAnyOf = {
  id: string;
  name: string;
  description: string;
  matchingType: PutReplacementsById200KeywordAnyOfMatchingType;
  categoryId: string;
  natureId: string;
  imageId: PutReplacementsById200KeywordAnyOfImageId;
  parentId: PutReplacementsById200KeywordAnyOfParentId;
  novelId: string;
  createdById: PutReplacementsById200KeywordAnyOfCreatedById;
  createdAt: PutReplacementsById200KeywordAnyOfCreatedAt;
  updatedAt: PutReplacementsById200KeywordAnyOfUpdatedAt;
};
