/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { ErrorType } from "../axios-instance";

import { customInstance } from "../axios-instance";
import type {
	DeleteKeywordsById200,
	DeleteKeywordsById404,
	DeleteKeywordsById500,
	GetKeywords200,
	GetKeywords404,
	GetKeywords500,
	GetKeywordsById200,
	GetKeywordsById404,
	GetKeywordsById500,
	GetKeywordsParams,
	PostKeywords200,
	PostKeywords404,
	PostKeywords500,
	PostKeywordsBodyOne,
	PostKeywordsBodyThree,
	PostKeywordsBodyTwo,
	PutKeywordsById200,
	PutKeywordsById404,
	PutKeywordsById500,
	PutKeywordsByIdBodyOne,
	PutKeywordsByIdBodyThree,
	PutKeywordsByIdBodyTwo,
} from "../schemas";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getKeywords = (
	params: GetKeywordsParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<GetKeywords200>(
		{ url: "http://localhost:7001/keywords/", method: "GET", params, signal },
		options,
	);
};

export const getGetKeywordsQueryKey = (params?: GetKeywordsParams) => {
	return [
		"http://localhost:7001/keywords/",
		...(params ? [params] : []),
	] as const;
};

export const getGetKeywordsQueryOptions = <
	TData = Awaited<ReturnType<typeof getKeywords>>,
	TError = ErrorType<GetKeywords404 | GetKeywords500>,
>(
	params: GetKeywordsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getKeywords>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetKeywordsQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getKeywords>>> = ({
		signal,
	}) => getKeywords(params, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getKeywords>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetKeywordsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getKeywords>>
>;
export type GetKeywordsQueryError = ErrorType<GetKeywords404 | GetKeywords500>;

export function useGetKeywords<
	TData = Awaited<ReturnType<typeof getKeywords>>,
	TError = ErrorType<GetKeywords404 | GetKeywords500>,
>(
	params: GetKeywordsParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getKeywords>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getKeywords>>,
					TError,
					Awaited<ReturnType<typeof getKeywords>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetKeywords<
	TData = Awaited<ReturnType<typeof getKeywords>>,
	TError = ErrorType<GetKeywords404 | GetKeywords500>,
>(
	params: GetKeywordsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getKeywords>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getKeywords>>,
					TError,
					Awaited<ReturnType<typeof getKeywords>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetKeywords<
	TData = Awaited<ReturnType<typeof getKeywords>>,
	TError = ErrorType<GetKeywords404 | GetKeywords500>,
>(
	params: GetKeywordsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getKeywords>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetKeywords<
	TData = Awaited<ReturnType<typeof getKeywords>>,
	TError = ErrorType<GetKeywords404 | GetKeywords500>,
>(
	params: GetKeywordsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getKeywords>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetKeywordsQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const postKeywords = (
	postKeywordsBody:
		| PostKeywordsBodyOne
		| PostKeywordsBodyTwo
		| PostKeywordsBodyThree,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<PostKeywords200>(
		{
			url: "http://localhost:7001/keywords/",
			method: "POST",
			data: postKeywordsBody,
			signal,
		},
		options,
	);
};

export const getPostKeywordsMutationOptions = <
	TError = ErrorType<PostKeywords404 | PostKeywords500>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postKeywords>>,
		TError,
		{ data: PostKeywordsBodyOne | PostKeywordsBodyTwo | PostKeywordsBodyThree },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postKeywords>>,
	TError,
	{ data: PostKeywordsBodyOne | PostKeywordsBodyTwo | PostKeywordsBodyThree },
	TContext
> => {
	const mutationKey = ["postKeywords"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postKeywords>>,
		{ data: PostKeywordsBodyOne | PostKeywordsBodyTwo | PostKeywordsBodyThree }
	> = (props) => {
		const { data } = props ?? {};

		return postKeywords(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostKeywordsMutationResult = NonNullable<
	Awaited<ReturnType<typeof postKeywords>>
>;
export type PostKeywordsMutationBody =
	| PostKeywordsBodyOne
	| PostKeywordsBodyTwo
	| PostKeywordsBodyThree;
export type PostKeywordsMutationError = ErrorType<
	PostKeywords404 | PostKeywords500
>;

export const usePostKeywords = <
	TError = ErrorType<PostKeywords404 | PostKeywords500>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postKeywords>>,
			TError,
			{
				data: PostKeywordsBodyOne | PostKeywordsBodyTwo | PostKeywordsBodyThree;
			},
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postKeywords>>,
	TError,
	{ data: PostKeywordsBodyOne | PostKeywordsBodyTwo | PostKeywordsBodyThree },
	TContext
> => {
	const mutationOptions = getPostKeywordsMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
export const getKeywordsById = (
	id: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<GetKeywordsById200>(
		{ url: `http://localhost:7001/keywords/${id}`, method: "GET", signal },
		options,
	);
};

export const getGetKeywordsByIdQueryKey = (id?: string) => {
	return [`http://localhost:7001/keywords/${id}`] as const;
};

export const getGetKeywordsByIdQueryOptions = <
	TData = Awaited<ReturnType<typeof getKeywordsById>>,
	TError = ErrorType<GetKeywordsById404 | GetKeywordsById500>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getKeywordsById>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetKeywordsByIdQueryKey(id);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getKeywordsById>>> = ({
		signal,
	}) => getKeywordsById(id, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getKeywordsById>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetKeywordsByIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof getKeywordsById>>
>;
export type GetKeywordsByIdQueryError = ErrorType<
	GetKeywordsById404 | GetKeywordsById500
>;

export function useGetKeywordsById<
	TData = Awaited<ReturnType<typeof getKeywordsById>>,
	TError = ErrorType<GetKeywordsById404 | GetKeywordsById500>,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getKeywordsById>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getKeywordsById>>,
					TError,
					Awaited<ReturnType<typeof getKeywordsById>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetKeywordsById<
	TData = Awaited<ReturnType<typeof getKeywordsById>>,
	TError = ErrorType<GetKeywordsById404 | GetKeywordsById500>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getKeywordsById>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getKeywordsById>>,
					TError,
					Awaited<ReturnType<typeof getKeywordsById>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetKeywordsById<
	TData = Awaited<ReturnType<typeof getKeywordsById>>,
	TError = ErrorType<GetKeywordsById404 | GetKeywordsById500>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getKeywordsById>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetKeywordsById<
	TData = Awaited<ReturnType<typeof getKeywordsById>>,
	TError = ErrorType<GetKeywordsById404 | GetKeywordsById500>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getKeywordsById>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetKeywordsByIdQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const putKeywordsById = (
	id: string,
	putKeywordsByIdBody:
		| PutKeywordsByIdBodyOne
		| PutKeywordsByIdBodyTwo
		| PutKeywordsByIdBodyThree,
	options?: SecondParameter<typeof customInstance>,
) => {
	return customInstance<PutKeywordsById200>(
		{
			url: `http://localhost:7001/keywords/${id}`,
			method: "PUT",
			data: putKeywordsByIdBody,
		},
		options,
	);
};

export const getPutKeywordsByIdMutationOptions = <
	TError = ErrorType<PutKeywordsById404 | PutKeywordsById500>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof putKeywordsById>>,
		TError,
		{
			id: string;
			data:
				| PutKeywordsByIdBodyOne
				| PutKeywordsByIdBodyTwo
				| PutKeywordsByIdBodyThree;
		},
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof putKeywordsById>>,
	TError,
	{
		id: string;
		data:
			| PutKeywordsByIdBodyOne
			| PutKeywordsByIdBodyTwo
			| PutKeywordsByIdBodyThree;
	},
	TContext
> => {
	const mutationKey = ["putKeywordsById"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof putKeywordsById>>,
		{
			id: string;
			data:
				| PutKeywordsByIdBodyOne
				| PutKeywordsByIdBodyTwo
				| PutKeywordsByIdBodyThree;
		}
	> = (props) => {
		const { id, data } = props ?? {};

		return putKeywordsById(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PutKeywordsByIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof putKeywordsById>>
>;
export type PutKeywordsByIdMutationBody =
	| PutKeywordsByIdBodyOne
	| PutKeywordsByIdBodyTwo
	| PutKeywordsByIdBodyThree;
export type PutKeywordsByIdMutationError = ErrorType<
	PutKeywordsById404 | PutKeywordsById500
>;

export const usePutKeywordsById = <
	TError = ErrorType<PutKeywordsById404 | PutKeywordsById500>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof putKeywordsById>>,
			TError,
			{
				id: string;
				data:
					| PutKeywordsByIdBodyOne
					| PutKeywordsByIdBodyTwo
					| PutKeywordsByIdBodyThree;
			},
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof putKeywordsById>>,
	TError,
	{
		id: string;
		data:
			| PutKeywordsByIdBodyOne
			| PutKeywordsByIdBodyTwo
			| PutKeywordsByIdBodyThree;
	},
	TContext
> => {
	const mutationOptions = getPutKeywordsByIdMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
export const deleteKeywordsById = (
	id: string,
	options?: SecondParameter<typeof customInstance>,
) => {
	return customInstance<DeleteKeywordsById200>(
		{ url: `http://localhost:7001/keywords/${id}`, method: "DELETE" },
		options,
	);
};

export const getDeleteKeywordsByIdMutationOptions = <
	TError = ErrorType<DeleteKeywordsById404 | DeleteKeywordsById500>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteKeywordsById>>,
		TError,
		{ id: string },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteKeywordsById>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["deleteKeywordsById"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteKeywordsById>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return deleteKeywordsById(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteKeywordsByIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteKeywordsById>>
>;

export type DeleteKeywordsByIdMutationError = ErrorType<
	DeleteKeywordsById404 | DeleteKeywordsById500
>;

export const useDeleteKeywordsById = <
	TError = ErrorType<DeleteKeywordsById404 | DeleteKeywordsById500>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteKeywordsById>>,
			TError,
			{ id: string },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteKeywordsById>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationOptions = getDeleteKeywordsByIdMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
