/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  DeleteReplacementsById200,
  DeleteReplacementsById404,
  DeleteReplacementsById500,
  GetReplacements200,
  GetReplacements404,
  GetReplacements500,
  GetReplacementsById200,
  GetReplacementsById404,
  GetReplacementsById500,
  GetReplacementsParams,
  PostReplacements200,
  PostReplacements404,
  PostReplacements500,
  PostReplacementsBodyOne,
  PostReplacementsBodyThree,
  PostReplacementsBodyTwo,
  PutReplacementsById200,
  PutReplacementsById404,
  PutReplacementsById500,
  PutReplacementsByIdBodyOne,
  PutReplacementsByIdBodyThree,
  PutReplacementsByIdBodyTwo,
} from '../schemas';

import { customInstance } from '../axios-instance';
import type { ErrorType } from '../axios-instance';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getReplacements = (
  params: GetReplacementsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetReplacements200>(
    { url: 'http://localhost:7001/replacements/', method: 'GET', params, signal },
    options,
  );
};

export const getGetReplacementsQueryKey = (params?: GetReplacementsParams) => {
  return [
    'http://localhost:7001/replacements/',
    ...(params ? [params] : []),
  ] as const;
};

export const getGetReplacementsQueryOptions = <
  TData = Awaited<ReturnType<typeof getReplacements>>,
  TError = ErrorType<GetReplacements404 | GetReplacements500>,
>(
  params: GetReplacementsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReplacements>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetReplacementsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getReplacements>>> = ({
    signal,
  }) => getReplacements(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getReplacements>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReplacementsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReplacements>>
>;
export type GetReplacementsQueryError = ErrorType<
  GetReplacements404 | GetReplacements500
>;

export function useGetReplacements<
  TData = Awaited<ReturnType<typeof getReplacements>>,
  TError = ErrorType<GetReplacements404 | GetReplacements500>,
>(
  params: GetReplacementsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReplacements>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReplacements>>,
          TError,
          Awaited<ReturnType<typeof getReplacements>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReplacements<
  TData = Awaited<ReturnType<typeof getReplacements>>,
  TError = ErrorType<GetReplacements404 | GetReplacements500>,
>(
  params: GetReplacementsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReplacements>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReplacements>>,
          TError,
          Awaited<ReturnType<typeof getReplacements>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReplacements<
  TData = Awaited<ReturnType<typeof getReplacements>>,
  TError = ErrorType<GetReplacements404 | GetReplacements500>,
>(
  params: GetReplacementsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReplacements>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetReplacements<
  TData = Awaited<ReturnType<typeof getReplacements>>,
  TError = ErrorType<GetReplacements404 | GetReplacements500>,
>(
  params: GetReplacementsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReplacements>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetReplacementsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const postReplacements = (
  postReplacementsBody:
    | PostReplacementsBodyOne
    | PostReplacementsBodyTwo
    | PostReplacementsBodyThree,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PostReplacements200>(
    {
      url: 'http://localhost:7001/replacements/',
      method: 'POST',
      data: postReplacementsBody,
      signal,
    },
    options,
  );
};

export const getPostReplacementsMutationOptions = <
  TError = ErrorType<PostReplacements404 | PostReplacements500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postReplacements>>,
    TError,
    {
      data:
        | PostReplacementsBodyOne
        | PostReplacementsBodyTwo
        | PostReplacementsBodyThree;
    },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postReplacements>>,
  TError,
  {
    data:
      | PostReplacementsBodyOne
      | PostReplacementsBodyTwo
      | PostReplacementsBodyThree;
  },
  TContext
> => {
  const mutationKey = ['postReplacements'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postReplacements>>,
    {
      data:
        | PostReplacementsBodyOne
        | PostReplacementsBodyTwo
        | PostReplacementsBodyThree;
    }
  > = (props) => {
    const { data } = props ?? {};

    return postReplacements(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostReplacementsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postReplacements>>
>;
export type PostReplacementsMutationBody =
  | PostReplacementsBodyOne
  | PostReplacementsBodyTwo
  | PostReplacementsBodyThree;
export type PostReplacementsMutationError = ErrorType<
  PostReplacements404 | PostReplacements500
>;

export const usePostReplacements = <
  TError = ErrorType<PostReplacements404 | PostReplacements500>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postReplacements>>,
      TError,
      {
        data:
          | PostReplacementsBodyOne
          | PostReplacementsBodyTwo
          | PostReplacementsBodyThree;
      },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postReplacements>>,
  TError,
  {
    data:
      | PostReplacementsBodyOne
      | PostReplacementsBodyTwo
      | PostReplacementsBodyThree;
  },
  TContext
> => {
  const mutationOptions = getPostReplacementsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getReplacementsById = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetReplacementsById200>(
    { url: `http://localhost:7001/replacements/${id}`, method: 'GET', signal },
    options,
  );
};

export const getGetReplacementsByIdQueryKey = (id?: string) => {
  return [`http://localhost:7001/replacements/${id}`] as const;
};

export const getGetReplacementsByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getReplacementsById>>,
  TError = ErrorType<GetReplacementsById404 | GetReplacementsById500>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReplacementsById>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetReplacementsByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getReplacementsById>>> = ({
    signal,
  }) => getReplacementsById(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getReplacementsById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReplacementsByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReplacementsById>>
>;
export type GetReplacementsByIdQueryError = ErrorType<
  GetReplacementsById404 | GetReplacementsById500
>;

export function useGetReplacementsById<
  TData = Awaited<ReturnType<typeof getReplacementsById>>,
  TError = ErrorType<GetReplacementsById404 | GetReplacementsById500>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReplacementsById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReplacementsById>>,
          TError,
          Awaited<ReturnType<typeof getReplacementsById>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReplacementsById<
  TData = Awaited<ReturnType<typeof getReplacementsById>>,
  TError = ErrorType<GetReplacementsById404 | GetReplacementsById500>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReplacementsById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReplacementsById>>,
          TError,
          Awaited<ReturnType<typeof getReplacementsById>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReplacementsById<
  TData = Awaited<ReturnType<typeof getReplacementsById>>,
  TError = ErrorType<GetReplacementsById404 | GetReplacementsById500>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReplacementsById>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetReplacementsById<
  TData = Awaited<ReturnType<typeof getReplacementsById>>,
  TError = ErrorType<GetReplacementsById404 | GetReplacementsById500>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReplacementsById>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetReplacementsByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const putReplacementsById = (
  id: string,
  putReplacementsByIdBody:
    | PutReplacementsByIdBodyOne
    | PutReplacementsByIdBodyTwo
    | PutReplacementsByIdBodyThree,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<PutReplacementsById200>(
    {
      url: `http://localhost:7001/replacements/${id}`,
      method: 'PUT',
      data: putReplacementsByIdBody,
    },
    options,
  );
};

export const getPutReplacementsByIdMutationOptions = <
  TError = ErrorType<PutReplacementsById404 | PutReplacementsById500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putReplacementsById>>,
    TError,
    {
      id: string;
      data:
        | PutReplacementsByIdBodyOne
        | PutReplacementsByIdBodyTwo
        | PutReplacementsByIdBodyThree;
    },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putReplacementsById>>,
  TError,
  {
    id: string;
    data:
      | PutReplacementsByIdBodyOne
      | PutReplacementsByIdBodyTwo
      | PutReplacementsByIdBodyThree;
  },
  TContext
> => {
  const mutationKey = ['putReplacementsById'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putReplacementsById>>,
    {
      id: string;
      data:
        | PutReplacementsByIdBodyOne
        | PutReplacementsByIdBodyTwo
        | PutReplacementsByIdBodyThree;
    }
  > = (props) => {
    const { id, data } = props ?? {};

    return putReplacementsById(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutReplacementsByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putReplacementsById>>
>;
export type PutReplacementsByIdMutationBody =
  | PutReplacementsByIdBodyOne
  | PutReplacementsByIdBodyTwo
  | PutReplacementsByIdBodyThree;
export type PutReplacementsByIdMutationError = ErrorType<
  PutReplacementsById404 | PutReplacementsById500
>;

export const usePutReplacementsById = <
  TError = ErrorType<PutReplacementsById404 | PutReplacementsById500>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putReplacementsById>>,
      TError,
      {
        id: string;
        data:
          | PutReplacementsByIdBodyOne
          | PutReplacementsByIdBodyTwo
          | PutReplacementsByIdBodyThree;
      },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putReplacementsById>>,
  TError,
  {
    id: string;
    data:
      | PutReplacementsByIdBodyOne
      | PutReplacementsByIdBodyTwo
      | PutReplacementsByIdBodyThree;
  },
  TContext
> => {
  const mutationOptions = getPutReplacementsByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteReplacementsById = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<DeleteReplacementsById200>(
    { url: `http://localhost:7001/replacements/${id}`, method: 'DELETE' },
    options,
  );
};

export const getDeleteReplacementsByIdMutationOptions = <
  TError = ErrorType<DeleteReplacementsById404 | DeleteReplacementsById500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteReplacementsById>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteReplacementsById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteReplacementsById'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteReplacementsById>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteReplacementsById(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteReplacementsByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteReplacementsById>>
>;

export type DeleteReplacementsByIdMutationError = ErrorType<
  DeleteReplacementsById404 | DeleteReplacementsById500
>;

export const useDeleteReplacementsById = <
  TError = ErrorType<DeleteReplacementsById404 | DeleteReplacementsById500>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteReplacementsById>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteReplacementsById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteReplacementsByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
